### ISSUE TITLE
How can I have automatic views?

### ISSUE THREAD

**Issue by mouillerart** [jqnatividad/ckanext-officedocs#10]
Hi,

I have installed the plugin and configured my production.ini as follows:

```
ckan.plugins = ... resource_proxy text_view image_view officedocs_view ...
ckan.views.default_views = image_view text_view officedocs_view recline_view
```

I can create views for XLS or ODS files manually, but for some reason, there is no automatic creation of the OfficeDocs view when I add a new dataset.

What am I missing?

Thanks

**Comment by slarrain** [comment]
Do you have [DataPusher](http://docs.ckan.org/projects/datapusher/en/latest/) installed?

**Comment by Aaron-M** [comment]
You also need to include officedocs in the default views

ckan.views.default_views = ... officedocs_view

**Comment by slarrain** [comment]
I didn't know that @Aaron-M. Thanks!
