### ISSUE TITLE
Excel files that previously worked with officedocs viewer now report error

### ISSUE THREAD

**Issue by Aaron-M** [jqnatividad/ckanext-officedocs#12]
We have used offcecdocs to preview some xlsx files successfully on Ckan 2.5.3.  Recently some excel files uploaded failed to work, so I began testing out if there was something in the file.  I created a very simple xlsx file and it still did not work.  I uploaded files that are in the system and officedocs is currently working, but the exact same file reuploaded in a separate dataset does not work with officedocs - shows an error message indicating the file might be unsupported or corrupt.

However, if instead of reuploading the file that is known to work, but rather link to it when creating the dataset, then officedocs preview works.

Any clues as to what we might have done that would create officedocs to stop working on newly uploaded files, but continue to work on files uploaded earlier?

**Comment by rossjones** [comment]
It *sounds* like once uploaded, the files might not be accessible to MS servers for some reason.  Has something changed recently?  Updated CKAN, or nginx config changes?

Can you compare the URLs of a working and a non-working excel file and see how they differ?

**Comment by jqnatividad** [comment]
Closing this old stale issue for now.  Don't hesitate to reopen if this is still a problem.
