### ISSUE TITLE
Add support for TSVs

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/ckanext-officedocs#7]
Officeviewer.com doesn't support TSVs, though Excel can open them directly.

A way around this is to use the Zoho Sheet Viewer which has the added benefit of also support OpenOffice spreadsheets.

cc @rossjones @talos

**Comment by rossjones** [comment]
Only seems to do a full-screen view, triggered by https://sheet.zoho.com/sheet/view.do?url=.... and then redirecting to a full-browser editor.  Which is neat I guess. Perhaps there should be an 'Open with...' option to open in your choice of online services?

Does the default data grid view in CKAN not support TSV?  That seems like the obvious place to do the fix.

**Comment by talos** [comment]
Since TSV is just a CSV with a tab instead of comma as delimiter, any CSV importer that can take a custom argument for delimiter should be able to handle them...  Is it just a matter of renaming the TSV to CSV, and letting the importer figure out the proper delimiter?

**Comment by jqnatividad** [comment]
Agreed.  TSV is just a hybrid of a CSV.

The main reason I opened this issue is so that we can view a TSV that's actually just a URL that CKAN is pointing to, so we don't need to re-upload it to the CKAN.

The full context of this issue is here - http://data.beta.nyc/dataset/nyc-2011-housing-and-vacancy-survey

**Comment by jqnatividad** [comment]
TSVs now supported by the datapusher with CKAN 2.5. :)

http://docs.ckan.org/en/latest/changelog.html

Still not closing this issue as admin may still prefer to configure a resource view of TSVs using this plugin.

**Comment by jqnatividad** [comment]
Closing this issue as TSVs are supported.
