### ISSUE TITLE
i wish it worked for me!

### ISSUE THREAD

**Issue by hengistthenord** [jqnatividad/ckanext-officedocs#8]
ckan install 2.4 on Ubuntu 12.04 

I get an error in the preview area of the items page but no errors in any log 
the doc is accessible from the link but is not previewed.

I have 

ckan.plugins = stats image_view text_view pdf_view webpage_view recline_prieview officedocs_view datastore datapusher resource_proxy viewhelpers pages odata customuserprivileges disqus

The site works and shows no other errors on screen other than for a doc or docx type which just will not display. I see the 'Office Previewer' type in the list of view types when manageing the viewer.

On install I get no error messages and every indication is that it installs, but does not work.

**Comment by rossjones** [comment]
Could you post the URL to one of your resources?  Either the resource page or the end document itself?

**Comment by hengistthenord** [comment]
I have found out now why it was not working. so for the benefit of others....
I was doing it in a test environment. the document was on my local - uploaded to the server behind a firewall. I undwerstand now that the plugin uses an external site which could not get back to my internal site.

On loading to an external ckan instance it still did not work this is because the external site does not work with an ip address eg http://192.168.1.31/ 

BUT hurrah it works fine with https://www.datanorthyorkshire.org/ the vailid url 
It works well and I am a happy chappy again.

I do think it would be helpful to explain why it will not work on an internal network or just ip in the notes as finding this information was not easy.
